spring:
  config:
    import: optional:application-secret.yml
  application:
    name: info-master

  profiles:
    default: dev # 개발 모드

  jpa:
    hibernate:
      ddl-auto:  validate  # 개발 단계만 create
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}

server:
  port: 8080

